//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace LunchCrawler.Data.Local
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LunchEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LunchEntities object using the connection string found in the 'LunchEntities' section of the application configuration file.
        /// </summary>
        public LunchEntities() : base("name=LunchEntities", "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LunchEntities object.
        /// </summary>
        public LunchEntities(string connectionString) : base(connectionString, "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LunchEntities object.
        /// </summary>
        public LunchEntities(EntityConnection connection) : base(connection, "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodKeyword> FoodKeywords
        {
            get
            {
                if ((_FoodKeywords == null))
                {
                    _FoodKeywords = base.CreateObjectSet<FoodKeyword>("FoodKeywords");
                }
                return _FoodKeywords;
            }
        }
        private ObjectSet<FoodKeyword> _FoodKeywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LunchMenuFeature> LunchMenuFeatures
        {
            get
            {
                if ((_LunchMenuFeatures == null))
                {
                    _LunchMenuFeatures = base.CreateObjectSet<LunchMenuFeature>("LunchMenuFeatures");
                }
                return _LunchMenuFeatures;
            }
        }
        private ObjectSet<LunchMenuFeature> _LunchMenuFeatures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LunchMenuKeyword> LunchMenuKeywords
        {
            get
            {
                if ((_LunchMenuKeywords == null))
                {
                    _LunchMenuKeywords = base.CreateObjectSet<LunchMenuKeyword>("LunchMenuKeywords");
                }
                return _LunchMenuKeywords;
            }
        }
        private ObjectSet<LunchMenuKeyword> _LunchMenuKeywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PotentialLunchMenu> PotentialLunchMenus
        {
            get
            {
                if ((_PotentialLunchMenus == null))
                {
                    _PotentialLunchMenus = base.CreateObjectSet<PotentialLunchMenu>("PotentialLunchMenus");
                }
                return _PotentialLunchMenus;
            }
        }
        private ObjectSet<PotentialLunchMenu> _PotentialLunchMenus;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodKeywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodKeywords(FoodKeyword foodKeyword)
        {
            base.AddObject("FoodKeywords", foodKeyword);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LunchMenuFeatures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLunchMenuFeatures(LunchMenuFeature lunchMenuFeature)
        {
            base.AddObject("LunchMenuFeatures", lunchMenuFeature);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LunchMenuKeywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLunchMenuKeywords(LunchMenuKeyword lunchMenuKeyword)
        {
            base.AddObject("LunchMenuKeywords", lunchMenuKeyword);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PotentialLunchMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPotentialLunchMenus(PotentialLunchMenu potentialLunchMenu)
        {
            base.AddObject("PotentialLunchMenus", potentialLunchMenu);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="FoodKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodKeyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodKeyword object.
        /// </summary>
        /// <param name="word">Initial value of the Word property.</param>
        public static FoodKeyword CreateFoodKeyword(global::System.String word)
        {
            FoodKeyword foodKeyword = new FoodKeyword();
            foodKeyword.Word = word;
            return foodKeyword;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                if (_Word != value)
                {
                    OnWordChanging(value);
                    ReportPropertyChanging("Word");
                    _Word = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Word");
                    OnWordChanged();
                }
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="LunchMenuFeature")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LunchMenuFeature : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LunchMenuFeature object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="restaurant">Initial value of the Restaurant property.</param>
        /// <param name="featureType">Initial value of the FeatureType property.</param>
        /// <param name="line">Initial value of the Line property.</param>
        /// <param name="linePosition">Initial value of the LinePosition property.</param>
        public static LunchMenuFeature CreateLunchMenuFeature(global::System.String id, global::System.String restaurant, global::System.Int32 featureType, global::System.Int32 line, global::System.Int32 linePosition)
        {
            LunchMenuFeature lunchMenuFeature = new LunchMenuFeature();
            lunchMenuFeature.id = id;
            lunchMenuFeature.Restaurant = restaurant;
            lunchMenuFeature.FeatureType = featureType;
            lunchMenuFeature.Line = line;
            lunchMenuFeature.LinePosition = linePosition;
            return lunchMenuFeature;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Restaurant
        {
            get
            {
                return _Restaurant;
            }
            set
            {
                OnRestaurantChanging(value);
                ReportPropertyChanging("Restaurant");
                _Restaurant = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Restaurant");
                OnRestaurantChanged();
            }
        }
        private global::System.String _Restaurant;
        partial void OnRestaurantChanging(global::System.String value);
        partial void OnRestaurantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureType
        {
            get
            {
                return _FeatureType;
            }
            set
            {
                OnFeatureTypeChanging(value);
                ReportPropertyChanging("FeatureType");
                _FeatureType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureType");
                OnFeatureTypeChanged();
            }
        }
        private global::System.Int32 _FeatureType;
        partial void OnFeatureTypeChanging(global::System.Int32 value);
        partial void OnFeatureTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Line
        {
            get
            {
                return _Line;
            }
            set
            {
                OnLineChanging(value);
                ReportPropertyChanging("Line");
                _Line = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Line");
                OnLineChanged();
            }
        }
        private global::System.Int32 _Line;
        partial void OnLineChanging(global::System.Int32 value);
        partial void OnLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LinePosition
        {
            get
            {
                return _LinePosition;
            }
            set
            {
                OnLinePositionChanging(value);
                ReportPropertyChanging("LinePosition");
                _LinePosition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LinePosition");
                OnLinePositionChanged();
            }
        }
        private global::System.Int32 _LinePosition;
        partial void OnLinePositionChanging(global::System.Int32 value);
        partial void OnLinePositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUsed
        {
            get
            {
                return _LastUsed;
            }
            set
            {
                OnLastUsedChanging(value);
                ReportPropertyChanging("LastUsed");
                _LastUsed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUsed");
                OnLastUsedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUsed;
        partial void OnLastUsedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUsedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="LunchMenuKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LunchMenuKeyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LunchMenuKeyword object.
        /// </summary>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="detectionCount">Initial value of the DetectionCount property.</param>
        public static LunchMenuKeyword CreateLunchMenuKeyword(global::System.String word, global::System.Int32 weight, global::System.Int64 detectionCount)
        {
            LunchMenuKeyword lunchMenuKeyword = new LunchMenuKeyword();
            lunchMenuKeyword.Word = word;
            lunchMenuKeyword.Weight = weight;
            lunchMenuKeyword.DetectionCount = detectionCount;
            return lunchMenuKeyword;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                if (_Word != value)
                {
                    OnWordChanging(value);
                    ReportPropertyChanging("Word");
                    _Word = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Word");
                    OnWordChanged();
                }
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Int32 _Weight;
        partial void OnWeightChanging(global::System.Int32 value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DetectionCount
        {
            get
            {
                return _DetectionCount;
            }
            set
            {
                OnDetectionCountChanging(value);
                ReportPropertyChanging("DetectionCount");
                _DetectionCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DetectionCount");
                OnDetectionCountChanged();
            }
        }
        private global::System.Int64 _DetectionCount;
        partial void OnDetectionCountChanging(global::System.Int64 value);
        partial void OnDetectionCountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="PotentialLunchMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PotentialLunchMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PotentialLunchMenu object.
        /// </summary>
        /// <param name="uRL">Initial value of the URL property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="totalPoints">Initial value of the TotalPoints property.</param>
        /// <param name="lunchMenuProbability">Initial value of the LunchMenuProbability property.</param>
        /// <param name="dateAdded">Initial value of the DateAdded property.</param>
        public static PotentialLunchMenu CreatePotentialLunchMenu(global::System.String uRL, global::System.Int32 status, global::System.Int32 totalPoints, global::System.Decimal lunchMenuProbability, global::System.DateTime dateAdded)
        {
            PotentialLunchMenu potentialLunchMenu = new PotentialLunchMenu();
            potentialLunchMenu.URL = uRL;
            potentialLunchMenu.Status = status;
            potentialLunchMenu.TotalPoints = totalPoints;
            potentialLunchMenu.LunchMenuProbability = lunchMenuProbability;
            potentialLunchMenu.DateAdded = dateAdded;
            return potentialLunchMenu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                if (_URL != value)
                {
                    OnURLChanging(value);
                    ReportPropertyChanging("URL");
                    _URL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("URL");
                    OnURLChanged();
                }
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiteHash
        {
            get
            {
                return _SiteHash;
            }
            set
            {
                OnSiteHashChanging(value);
                ReportPropertyChanging("SiteHash");
                _SiteHash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SiteHash");
                OnSiteHashChanged();
            }
        }
        private global::System.String _SiteHash;
        partial void OnSiteHashChanging(global::System.String value);
        partial void OnSiteHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalPoints
        {
            get
            {
                return _TotalPoints;
            }
            set
            {
                OnTotalPointsChanging(value);
                ReportPropertyChanging("TotalPoints");
                _TotalPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPoints");
                OnTotalPointsChanged();
            }
        }
        private global::System.Int32 _TotalPoints;
        partial void OnTotalPointsChanging(global::System.Int32 value);
        partial void OnTotalPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LunchMenuProbability
        {
            get
            {
                return _LunchMenuProbability;
            }
            set
            {
                OnLunchMenuProbabilityChanging(value);
                ReportPropertyChanging("LunchMenuProbability");
                _LunchMenuProbability = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LunchMenuProbability");
                OnLunchMenuProbabilityChanged();
            }
        }
        private global::System.Decimal _LunchMenuProbability;
        partial void OnLunchMenuProbabilityChanging(global::System.Decimal value);
        partial void OnLunchMenuProbabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalKeywordDetections
        {
            get
            {
                return _TotalKeywordDetections;
            }
            set
            {
                OnTotalKeywordDetectionsChanging(value);
                ReportPropertyChanging("TotalKeywordDetections");
                _TotalKeywordDetections = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalKeywordDetections");
                OnTotalKeywordDetectionsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalKeywordDetections;
        partial void OnTotalKeywordDetectionsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalKeywordDetectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ExactKeywordDetections
        {
            get
            {
                return _ExactKeywordDetections;
            }
            set
            {
                OnExactKeywordDetectionsChanging(value);
                ReportPropertyChanging("ExactKeywordDetections");
                _ExactKeywordDetections = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExactKeywordDetections");
                OnExactKeywordDetectionsChanged();
            }
        }
        private Nullable<global::System.Int32> _ExactKeywordDetections;
        partial void OnExactKeywordDetectionsChanging(Nullable<global::System.Int32> value);
        partial void OnExactKeywordDetectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PartialKeywordDetections
        {
            get
            {
                return _PartialKeywordDetections;
            }
            set
            {
                OnPartialKeywordDetectionsChanging(value);
                ReportPropertyChanging("PartialKeywordDetections");
                _PartialKeywordDetections = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartialKeywordDetections");
                OnPartialKeywordDetectionsChanged();
            }
        }
        private Nullable<global::System.Int32> _PartialKeywordDetections;
        partial void OnPartialKeywordDetectionsChanging(Nullable<global::System.Int32> value);
        partial void OnPartialKeywordDetectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FuzzyKeywordDetections
        {
            get
            {
                return _FuzzyKeywordDetections;
            }
            set
            {
                OnFuzzyKeywordDetectionsChanging(value);
                ReportPropertyChanging("FuzzyKeywordDetections");
                _FuzzyKeywordDetections = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FuzzyKeywordDetections");
                OnFuzzyKeywordDetectionsChanged();
            }
        }
        private Nullable<global::System.Int32> _FuzzyKeywordDetections;
        partial void OnFuzzyKeywordDetectionsChanging(Nullable<global::System.Int32> value);
        partial void OnFuzzyKeywordDetectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();

        #endregion
    
    }

    #endregion
    
}
