//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Lunch.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LunchEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LunchEntities object using the connection string found in the 'LunchEntities' section of the application configuration file.
        /// </summary>
        public LunchEntities() : base("name=LunchEntities", "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LunchEntities object.
        /// </summary>
        public LunchEntities(string connectionString) : base(connectionString, "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LunchEntities object.
        /// </summary>
        public LunchEntities(EntityConnection connection) : base(connection, "LunchEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodKeyword> FoodKeywords
        {
            get
            {
                if ((_FoodKeywords == null))
                {
                    _FoodKeywords = base.CreateObjectSet<FoodKeyword>("FoodKeywords");
                }
                return _FoodKeywords;
            }
        }
        private ObjectSet<FoodKeyword> _FoodKeywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LunchMenuFeature> LunchMenuFeatures
        {
            get
            {
                if ((_LunchMenuFeatures == null))
                {
                    _LunchMenuFeatures = base.CreateObjectSet<LunchMenuFeature>("LunchMenuFeatures");
                }
                return _LunchMenuFeatures;
            }
        }
        private ObjectSet<LunchMenuFeature> _LunchMenuFeatures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BasicFoodKeyword> BasicFoodKeywords
        {
            get
            {
                if ((_BasicFoodKeywords == null))
                {
                    _BasicFoodKeywords = base.CreateObjectSet<BasicFoodKeyword>("BasicFoodKeywords");
                }
                return _BasicFoodKeywords;
            }
        }
        private ObjectSet<BasicFoodKeyword> _BasicFoodKeywords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodKeywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodKeywords(FoodKeyword foodKeyword)
        {
            base.AddObject("FoodKeywords", foodKeyword);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LunchMenuFeatures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLunchMenuFeatures(LunchMenuFeature lunchMenuFeature)
        {
            base.AddObject("LunchMenuFeatures", lunchMenuFeature);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BasicFoodKeywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBasicFoodKeywords(BasicFoodKeyword basicFoodKeyword)
        {
            base.AddObject("BasicFoodKeywords", basicFoodKeyword);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="BasicFoodKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BasicFoodKeyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BasicFoodKeyword object.
        /// </summary>
        /// <param name="word">Initial value of the Word property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        public static BasicFoodKeyword CreateBasicFoodKeyword(global::System.String word, global::System.Int32 weight)
        {
            BasicFoodKeyword basicFoodKeyword = new BasicFoodKeyword();
            basicFoodKeyword.Word = word;
            basicFoodKeyword.Weight = weight;
            return basicFoodKeyword;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                if (_Word != value)
                {
                    OnWordChanging(value);
                    ReportPropertyChanging("Word");
                    _Word = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Word");
                    OnWordChanged();
                }
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Int32 _Weight;
        partial void OnWeightChanging(global::System.Int32 value);
        partial void OnWeightChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="FoodKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodKeyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodKeyword object.
        /// </summary>
        /// <param name="word">Initial value of the Word property.</param>
        public static FoodKeyword CreateFoodKeyword(global::System.String word)
        {
            FoodKeyword foodKeyword = new FoodKeyword();
            foodKeyword.Word = word;
            return foodKeyword;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Word
        {
            get
            {
                return _Word;
            }
            set
            {
                if (_Word != value)
                {
                    OnWordChanging(value);
                    ReportPropertyChanging("Word");
                    _Word = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Word");
                    OnWordChanged();
                }
            }
        }
        private global::System.String _Word;
        partial void OnWordChanging(global::System.String value);
        partial void OnWordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LunchModel", Name="LunchMenuFeature")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LunchMenuFeature : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LunchMenuFeature object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="restaurant">Initial value of the Restaurant property.</param>
        /// <param name="featureType">Initial value of the FeatureType property.</param>
        /// <param name="line">Initial value of the Line property.</param>
        /// <param name="linePosition">Initial value of the LinePosition property.</param>
        public static LunchMenuFeature CreateLunchMenuFeature(global::System.String id, global::System.String restaurant, global::System.Int32 featureType, global::System.Int32 line, global::System.Int32 linePosition)
        {
            LunchMenuFeature lunchMenuFeature = new LunchMenuFeature();
            lunchMenuFeature.id = id;
            lunchMenuFeature.Restaurant = restaurant;
            lunchMenuFeature.FeatureType = featureType;
            lunchMenuFeature.Line = line;
            lunchMenuFeature.LinePosition = linePosition;
            return lunchMenuFeature;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Restaurant
        {
            get
            {
                return _Restaurant;
            }
            set
            {
                OnRestaurantChanging(value);
                ReportPropertyChanging("Restaurant");
                _Restaurant = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Restaurant");
                OnRestaurantChanged();
            }
        }
        private global::System.String _Restaurant;
        partial void OnRestaurantChanging(global::System.String value);
        partial void OnRestaurantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeatureType
        {
            get
            {
                return _FeatureType;
            }
            set
            {
                OnFeatureTypeChanging(value);
                ReportPropertyChanging("FeatureType");
                _FeatureType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FeatureType");
                OnFeatureTypeChanged();
            }
        }
        private global::System.Int32 _FeatureType;
        partial void OnFeatureTypeChanging(global::System.Int32 value);
        partial void OnFeatureTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Line
        {
            get
            {
                return _Line;
            }
            set
            {
                OnLineChanging(value);
                ReportPropertyChanging("Line");
                _Line = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Line");
                OnLineChanged();
            }
        }
        private global::System.Int32 _Line;
        partial void OnLineChanging(global::System.Int32 value);
        partial void OnLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LinePosition
        {
            get
            {
                return _LinePosition;
            }
            set
            {
                OnLinePositionChanging(value);
                ReportPropertyChanging("LinePosition");
                _LinePosition = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LinePosition");
                OnLinePositionChanged();
            }
        }
        private global::System.Int32 _LinePosition;
        partial void OnLinePositionChanging(global::System.Int32 value);
        partial void OnLinePositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUsed
        {
            get
            {
                return _LastUsed;
            }
            set
            {
                OnLastUsedChanging(value);
                ReportPropertyChanging("LastUsed");
                _LastUsed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUsed");
                OnLastUsedChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUsed;
        partial void OnLastUsedChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUsedChanged();

        #endregion
    
    }

    #endregion
    
}
